name: thesis

channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip

  - pyarrow
  - pandas
  - numpy
  - dask
  - cudf=0.19
  - cudatoolkit=11.0
  - xlrd
  - openpyxl
  - python-dotenv
  - matplotlib
  - modin

  - pymapd

  - jupyterlab
  - anaconda::ipykernel
  - jupyterlab-git
  - jupyterlab-lsp
  - python-language-server[flake8]
  - black
  - isort
  - jupyterlab_code_formatter
  - dvc
  
  - pip:
    - jupyterlab-sublime
